// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'models/score_history_entry.dart';
import 'models/score_reason.dart';
import 'models/score_user.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
    id: const obx_int.IdUid(1, 5129664310427820535),
    name: 'ScoreUser',
    lastPropertyId: const obx_int.IdUid(3, 1747462342931214378),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4573054970992775381),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 8120673109299526800),
        name: 'name',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 1747462342931214378),
        name: 'score',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(2, 8095024443570221459),
    name: 'ScoreHistoryEntry',
    lastPropertyId: const obx_int.IdUid(5, 5737414133214264127),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 4427927214551890156),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 7502618915735011085),
        name: 'userName',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 5217357705372808917),
        name: 'delta',
        type: 6,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(4, 5115785778920933331),
        name: 'reason',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(5, 5737414133214264127),
        name: 'timestamp',
        type: 10,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
  obx_int.ModelEntity(
    id: const obx_int.IdUid(3, 2250441183958670419),
    name: 'ScoreReason',
    lastPropertyId: const obx_int.IdUid(3, 2435331068842080532),
    flags: 0,
    properties: <obx_int.ModelProperty>[
      obx_int.ModelProperty(
        id: const obx_int.IdUid(1, 6764526366783414864),
        name: 'id',
        type: 6,
        flags: 1,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(2, 5460127457369345864),
        name: 'label',
        type: 9,
        flags: 0,
      ),
      obx_int.ModelProperty(
        id: const obx_int.IdUid(3, 2435331068842080532),
        name: 'delta',
        type: 6,
        flags: 0,
      ),
    ],
    relations: <obx_int.ModelRelation>[],
    backlinks: <obx_int.ModelBacklink>[],
  ),
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore({
  String? directory,
  int? maxDBSizeInKB,
  int? maxDataSizeInKB,
  int? fileMode,
  int? maxReaders,
  bool queriesCaseSensitiveDefault = true,
  String? macosApplicationGroup,
}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(
    getObjectBoxModel(),
    directory: directory ?? (await defaultStoreDirectory()).path,
    maxDBSizeInKB: maxDBSizeInKB,
    maxDataSizeInKB: maxDataSizeInKB,
    fileMode: fileMode,
    maxReaders: maxReaders,
    queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
    macosApplicationGroup: macosApplicationGroup,
  );
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
    // If this version is not found, it means that this file was generated
    // with an older version of the ObjectBox Dart generator.
    // Please regenerate this file with the current generator version.
    // Typically, this is done with `dart run build_runner build`.
    generatorVersion: obx_int.GeneratorVersion.v2025_12_16,
    entities: _entities,
    lastEntityId: const obx_int.IdUid(3, 2250441183958670419),
    lastIndexId: const obx_int.IdUid(0, 0),
    lastRelationId: const obx_int.IdUid(0, 0),
    lastSequenceId: const obx_int.IdUid(0, 0),
    retiredEntityUids: const [],
    retiredIndexUids: const [],
    retiredPropertyUids: const [],
    retiredRelationUids: const [],
    modelVersion: 5,
    modelVersionParserMinimum: 5,
    version: 1,
  );

  final bindings = <Type, obx_int.EntityDefinition>{
    ScoreUser: obx_int.EntityDefinition<ScoreUser>(
      model: _entities[0],
      toOneRelations: (ScoreUser object) => [],
      toManyRelations: (ScoreUser object) => {},
      getId: (ScoreUser object) => object.id,
      setId: (ScoreUser object, int id) {
        object.id = id;
      },
      objectToFB: (ScoreUser object, fb.Builder fbb) {
        final nameOffset = fbb.writeString(object.name);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, nameOffset);
        fbb.addInt64(2, object.score);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final nameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final scoreParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final object = ScoreUser(
          name: nameParam,
          id: idParam,
          score: scoreParam,
        );

        return object;
      },
    ),
    ScoreHistoryEntry: obx_int.EntityDefinition<ScoreHistoryEntry>(
      model: _entities[1],
      toOneRelations: (ScoreHistoryEntry object) => [],
      toManyRelations: (ScoreHistoryEntry object) => {},
      getId: (ScoreHistoryEntry object) => object.id,
      setId: (ScoreHistoryEntry object, int id) {
        object.id = id;
      },
      objectToFB: (ScoreHistoryEntry object, fb.Builder fbb) {
        final userNameOffset = fbb.writeString(object.userName);
        final reasonOffset = fbb.writeString(object.reason);
        fbb.startTable(6);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, userNameOffset);
        fbb.addInt64(2, object.delta);
        fbb.addOffset(3, reasonOffset);
        fbb.addInt64(4, object.timestamp.millisecondsSinceEpoch);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final userNameParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final deltaParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final reasonParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 10, '');
        final timestampParam = DateTime.fromMillisecondsSinceEpoch(
          const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
          isUtc: true,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = ScoreHistoryEntry(
          userName: userNameParam,
          delta: deltaParam,
          reason: reasonParam,
          timestamp: timestampParam,
          id: idParam,
        );

        return object;
      },
    ),
    ScoreReason: obx_int.EntityDefinition<ScoreReason>(
      model: _entities[2],
      toOneRelations: (ScoreReason object) => [],
      toManyRelations: (ScoreReason object) => {},
      getId: (ScoreReason object) => object.id,
      setId: (ScoreReason object, int id) {
        object.id = id;
      },
      objectToFB: (ScoreReason object, fb.Builder fbb) {
        final labelOffset = fbb.writeString(object.label);
        fbb.startTable(4);
        fbb.addInt64(0, object.id);
        fbb.addOffset(1, labelOffset);
        fbb.addInt64(2, object.delta);
        fbb.finish(fbb.endTable());
        return object.id;
      },
      objectFromFB: (obx.Store store, ByteData fbData) {
        final buffer = fb.BufferContext(fbData);
        final rootOffset = buffer.derefObject(0);
        final labelParam = const fb.StringReader(
          asciiOptimization: true,
        ).vTableGet(buffer, rootOffset, 6, '');
        final deltaParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          8,
          0,
        );
        final idParam = const fb.Int64Reader().vTableGet(
          buffer,
          rootOffset,
          4,
          0,
        );
        final object = ScoreReason(
          label: labelParam,
          delta: deltaParam,
          id: idParam,
        );

        return object;
      },
    ),
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [ScoreUser] entity fields to define ObjectBox queries.
class ScoreUser_ {
  /// See [ScoreUser.id].
  static final id = obx.QueryIntegerProperty<ScoreUser>(
    _entities[0].properties[0],
  );

  /// See [ScoreUser.name].
  static final name = obx.QueryStringProperty<ScoreUser>(
    _entities[0].properties[1],
  );

  /// See [ScoreUser.score].
  static final score = obx.QueryIntegerProperty<ScoreUser>(
    _entities[0].properties[2],
  );
}

/// [ScoreHistoryEntry] entity fields to define ObjectBox queries.
class ScoreHistoryEntry_ {
  /// See [ScoreHistoryEntry.id].
  static final id = obx.QueryIntegerProperty<ScoreHistoryEntry>(
    _entities[1].properties[0],
  );

  /// See [ScoreHistoryEntry.userName].
  static final userName = obx.QueryStringProperty<ScoreHistoryEntry>(
    _entities[1].properties[1],
  );

  /// See [ScoreHistoryEntry.delta].
  static final delta = obx.QueryIntegerProperty<ScoreHistoryEntry>(
    _entities[1].properties[2],
  );

  /// See [ScoreHistoryEntry.reason].
  static final reason = obx.QueryStringProperty<ScoreHistoryEntry>(
    _entities[1].properties[3],
  );

  /// See [ScoreHistoryEntry.timestamp].
  static final timestamp = obx.QueryDateProperty<ScoreHistoryEntry>(
    _entities[1].properties[4],
  );
}

/// [ScoreReason] entity fields to define ObjectBox queries.
class ScoreReason_ {
  /// See [ScoreReason.id].
  static final id = obx.QueryIntegerProperty<ScoreReason>(
    _entities[2].properties[0],
  );

  /// See [ScoreReason.label].
  static final label = obx.QueryStringProperty<ScoreReason>(
    _entities[2].properties[1],
  );

  /// See [ScoreReason.delta].
  static final delta = obx.QueryIntegerProperty<ScoreReason>(
    _entities[2].properties[2],
  );
}
